# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: miiSpace
email: miigotu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is just a place to collect my projects and information about them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: miigotu
github_username:  miigotu

github:
  repository_url: https://github.com/miigotu

favicon:
  source: favicon.svg
  path: assets/images
  svg:
    density: 1200
 
sass:
  # loading path from site root
  # default to _sass
  sass_dir: node_modules/bootstrap-sass/assets/stylesheets
  style: compressed

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  #- jekyll-minifier
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-admin
  - jekyll-paginate
  - jekyll-default-layout
  - jekyll-favicon
  - jekyll-optional-front-matter

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - yarn.lock
   - package.json
#   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .idea
